-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 15:07:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema discogsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema discogsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discogsdb` DEFAULT CHARACTER SET utf8 ;
USE `discogsdb` ;

-- -----------------------------------------------------
-- Table `discogsdb`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discogsdb`.`labels` (
  `id` INT UNSIGNED NOT NULL,
  `labels` TEXT NULL,
  `contactinfo` TEXT NULL,
  `profile` TEXT NULL,
  `data_quality` TEXT NULL,
  `url` TEXT NULL,
  `label` TEXT NULL,
  `parentlabel` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discogsdb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discogsdb`.`artists` (
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discogsdb`.`aliasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discogsdb`.`aliasses` (
  `name` VARCHAR(255) NOT NULL,
  `artists_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_aliasses_artists_idx` (`artists_id` ASC),
  CONSTRAINT `fk_aliasses_artists`
    FOREIGN KEY (`artists_id`)
    REFERENCES `discogsdb`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
